# Generated by Django 6.0.3 on 2026-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='product',
            field=models.CharField(blank=True, choices=[('boyshort', 'Boyshort'), ('shapewear', 'Shapewear'), ('briefs', 'Briefs')], max_length=50),
        ),
    ]
