# Generated by Django 6.0.3 on 2026-04-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField(blank=True)),
                ('customer_persona', models.CharField(blank=True, max_length=50)),
                ('number_of_ads', models.PositiveIntegerField(default=5)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('placement', models.CharField(blank=True, max_length=50)),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
