# Generated by Django 6.0.3 on 2026-04-06 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_customerpersona_alter_adgroup_customer_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('style', 'Style Reference'), ('product', 'Product Reference')], max_length=20)),
                ('image', models.ImageField(upload_to='assets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='adgroup',
            name='product_references',
            field=models.ManyToManyField(blank=True, limit_choices_to={'asset_type': 'product'}, related_name='ad_groups_as_product', to='campaigns.asset'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='style_references',
            field=models.ManyToManyField(blank=True, limit_choices_to={'asset_type': 'style'}, related_name='ad_groups_as_style', to='campaigns.asset'),
        ),
    ]
