# Generated by Django 6.0.3 on 2026-04-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_asset_adgroup_product_references_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdGroup',
            new_name='Generator',
        ),
        migrations.AlterField(
            model_name='generator',
            name='campaign',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='generators',
                to='campaigns.campaign',
            ),
        ),
        migrations.AlterField(
            model_name='generator',
            name='customer_persona',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='generators',
                to='campaigns.customerpersona',
            ),
        ),
    ]
