# Generated by Django 6.0.3 on 2026-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_rename_adgroup_to_generator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generator',
            name='product_references',
            field=models.ManyToManyField(blank=True, limit_choices_to={'asset_type': 'product'}, related_name='generators_as_product', to='campaigns.asset'),
        ),
        migrations.AlterField(
            model_name='generator',
            name='style_references',
            field=models.ManyToManyField(blank=True, limit_choices_to={'asset_type': 'style'}, related_name='generators_as_style', to='campaigns.asset'),
        ),
    ]
