# Generated by Django 6.0.3 on 2026-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_ad_admessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='generator',
            name='headlines',
            field=models.TextField(blank=True, help_text='Headlines for the ads, one per line'),
        ),
    ]
