# Generated by Django 6.0.3 on 2026-04-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_add_status_to_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='generation_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores generation context (prompt, references) for revisions'),
        ),
    ]
