# Generated by Django 6.0.3 on 2026-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_apisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.0-flash-preview-image-generation', 'Gemini 2.0 Flash (Image Gen Preview)'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-3-pro-image-preview', 'Gemini 3 Pro (Image Preview)')], default='gemini-2.0-flash-preview-image-generation', help_text='Gemini model to use for image generation', max_length=100),
        ),
    ]
