# Generated by Django 6.0.3 on 2026-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_apisettings_gemini_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (Fast)'), ('gemini-3.1-flash-image-preview', 'Gemini 3.1 Flash Image Preview (High Volume)'), ('gemini-3-pro-image-preview', 'Gemini 3 Pro Image Preview (Professional)')], default='gemini-2.5-flash-image', help_text='Gemini model to use for image generation', max_length=100),
        ),
    ]
