# Generated by Django 6.0.3 on 2026-04-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_alter_apisettings_gemini_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='primary_provider',
            field=models.CharField(choices=[('gemini', 'Gemini (Primary) → OpenAI (Fallback)'), ('openai', 'OpenAI (Primary) → Gemini (Fallback)'), ('gemini_only', 'Gemini Only'), ('openai_only', 'OpenAI Only')], default='gemini', help_text='Which AI provider to use for image generation', max_length=20),
        ),
    ]
