# Generated by Django 6.0.3 on 2026-04-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_apisettings_primary_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='master_prompt',
            field=models.TextField(blank=True, default='', help_text='Master prompt instructions for image generation'),
        ),
    ]
