# Generated by Django 6.0.3 on 2026-04-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_add_master_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='critique_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full CritiqueResult data for analysis'),
        ),
        migrations.AddField(
            model_name='ad',
            name='critique_passed',
            field=models.BooleanField(default=True, help_text='Whether image passed all 7 quality checks'),
        ),
        migrations.AddField(
            model_name='ad',
            name='critique_score',
            field=models.FloatField(blank=True, help_text='Overall quality score (1-10) from ImageCritic', null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='critique_summary',
            field=models.TextField(blank=True, help_text='Summary of critique result'),
        ),
        migrations.AddField(
            model_name='ad',
            name='revision_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of auto-revisions performed'),
        ),
        migrations.AddField(
            model_name='ad',
            name='was_auto_revised',
            field=models.BooleanField(default=False, help_text='Whether this image was auto-revised by critique system'),
        ),
    ]
