# Generated by Django 6.0.3 on 2026-04-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_add_critique_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='critic_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash (Fast)'), ('gemini-2.5-flash-preview-05-20', 'Gemini 2.5 Flash Preview'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro Preview')], default='gemini-2.0-flash', help_text='Model for image quality critique', max_length=100),
        ),
    ]
