# Generated by Django 6.0.3 on 2026-04-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_add_critic_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='critic_max_retries',
            field=models.PositiveSmallIntegerField(default=3, help_text='Max retries for critic API rate limits (0-10)'),
        ),
    ]
