# Generated by Django 6.0.3 on 2026-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_update_critic_model_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReference',
            fields=[
            ],
            options={
                'verbose_name': 'Product Reference',
                'verbose_name_plural': 'Product References',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.asset',),
        ),
        migrations.CreateModel(
            name='StyleReference',
            fields=[
            ],
            options={
                'verbose_name': 'Style Reference',
                'verbose_name_plural': 'Style References',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('campaigns.asset',),
        ),
        migrations.AddField(
            model_name='generator',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generator',
            name='total_expected',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
