# Generated by Django 6.0.3 on 2026-04-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0027_generator_cancelled_status_and_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='image_temperature',
            field=models.FloatField(default=1.0, help_text='Sampling temperature for Gemini image generation (0.0–2.0). Lower = more faithful to reference images and instructions. Note: Gemini 3 image models have historically shown severe latency degradation below 1.0 — test before lowering in prod.'),
        ),
    ]
